---
title: "Etherscan API Evaluation"
author: "Olivia Modesto"
date: "2025-03-05"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
bibliography: references.bib
nocite: '@*'
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Analysis

- la parte di Etherscan vale anche qui \
- layout area personale e come generare una nuova chiave \
- richiede conoscenze di programmazione \
- Nielsen meno diretto \
- i dati sono dettagliati \
- richiede conoscere le hash \
- richiede tempo se non si conoscono i numeri dei blocchi di interesse \
- docs.etherscan.io fornisce una documentazione dettagliata \
- esistono funzioni specifiche, da usare come url \
- che endpoints sono resi disponibili con Etherscan API ? \
  - Accounts \
  - Contracts \
  - Transactions \
  - Blocks \
  - Logs \
  - Geth/Parity Proxy \
  - Tokens \
  - Gas Tracker \
  - Stats \
\
  API PRO \
  - Etherscan API PRO \
  - API PRO Endpoints \
  - Metadata API \
- Estrarre dati con meno limitazioni rispetto a Etherscan \
- &Egrave; possibile creare un nodo \
- &Egrave; possibile interagire con i contratti \
- Etherscan API espande le funzionalità, ma richiede competenze più avanzate di programmazione \
- 